name: Pylint

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'main.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout my source code from github
      uses: actions/checkout@v4

    - name: Analysing the code with pylint
      run: |
        docker build -t app:v1 .
