name: Pylint

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'main.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout my source code from github
      uses: actions/checkout@v4

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: shkatara/prerna
        registry: docker.io
        username: shkatara
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: inclass