name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout my source code from github
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Hello there
      run: |
        echo Hi this is an agent

    - name: Analysing the code with pylint
      run: |
        pylint main.py
